"""ORION EDI writer + the send ledger (#64).

ORION reads a fixed-width file: a column shifted by one character is a wrong order. The
layout below is a faithful port of the production `ASSEMBLE AND GENERATE EDI` Code node,
and `tests/fixtures/edi_reference.json` holds bytes generated by running THAT node under
node — so the test is parity with what the warehouse receives today.

The ledger closes the duplicate-upload risk (#51): (customer, delivery date, content
hash) may be claimed once. A failed upload releases its claim so the order can be retried.
"""
from __future__ import annotations

import hashlib
import logging
import re
import time
import unicodedata
from dataclasses import dataclass
from datetime import UTC, datetime

import psycopg

from . import claim as claim_mod

log = logging.getLogger("orders.edi")

SUPPLIER_EAN = "8586013743063"
SUPPLIER_NAME = "SLOVNORMAL, s.r.o."
HEADER_WIDTH = 1157
ORION_DIR = "C:\\ORION\\COMMUNICATOR\\data\\in"
# ORION truncates a longer PO; the tail is the significant part.
MAX_ORDER_NUMBER = 15

_DIACRITICS = {
    "á": "a", "ä": "a", "č": "c", "ď": "d", "é": "e", "í": "i", "ĺ": "l", "ľ": "l",
    "ň": "n", "ó": "o", "ô": "o", "ŕ": "r", "š": "s", "ť": "t", "ú": "u", "ý": "y",
    "ž": "z",
}


@dataclass
class Edi:
    content: str
    line_count: int
    skipped: list[str]


def _strip_diacritics(text: str) -> str:
    """Fold to ASCII the way the production generator does.

    It maps the Slovak letters explicitly and leaves anything else alone, so characters
    like "–" or "ĽŠŤ" that are NOT in its table survive there — here they are folded via
    NFKD and finally dropped, because ORION's fixed-width reader is ASCII. Both paths
    agree on every character the live pipeline actually emits (pinned by the fixture).
    """
    out = []
    for ch in str(text or ""):
        mapped = _DIACRITICS.get(ch) or _DIACRITICS.get(ch.lower())
        if mapped:
            out.append(mapped.upper() if ch.isupper() else mapped)
            continue
        if ord(ch) < 128:
            out.append(ch)
            continue
        folded = "".join(c for c in unicodedata.normalize("NFKD", ch)
                         if not unicodedata.combining(c))
        out.append("".join(c for c in folded if ord(c) < 128))
    return "".join(out)


def _pad(text, width: int) -> str:
    s = _strip_diacritics(text)
    return s[:width] if len(s) >= width else s + " " * (width - len(s))


def _pad_left(text, width: int) -> str:
    s = str(text or "")
    return s[:width] if len(s) >= width else " " * (width - len(s)) + s


def _format_date(value: str) -> str:
    """YYYYMMDD from DD.MM.YYYY or ISO; 8 spaces when there is no usable date.

    Both shapes are accepted because the verify stage sometimes reformats the delivery
    date to ISO — dropping it from the header would lose the expedition date.
    """
    s = str(value or "").strip()
    iso = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", s)
    if iso:
        return iso.group(1) + iso.group(2) + iso.group(3)
    parts = s.split(".")
    if len(parts) != 3:
        return " " * 8
    year = parts[2].strip()
    if len(year) == 2:
        year = "20" + year
    return year + parts[1].strip().rjust(2, "0") + parts[0].strip().rjust(2, "0")


def _today() -> str:
    return datetime.now(UTC).strftime("%Y%m%d")


def build(ean: str, store: str, orderNumber: str, deliveryDate: str,  # noqa: N803
          items: list[dict], today: str = "") -> Edi:
    """The fixed-width document. Unmatched items are skipped and returned by name.

    Parameter names match the production node's arguments so the fixture can be applied
    with `**case["input"]` and any drift shows up as a byte diff.
    """
    order_no = str(orderNumber or "")[-MAX_ORDER_NUMBER:]
    store_name = _strip_diacritics(store or "Zakaznik")
    ean = str(ean or "")

    hdr = ("HDR" + _pad(SUPPLIER_EAN, 13) + "  " + _pad(order_no, 15) + _pad("", 14)
           + (today or _today()) + "   ")
    hdr += (_pad(ean, 17) + _pad(store_name, 50) + _pad("", 50) + _pad("", 50)
            + _pad("", 30) + _pad("", 15) + _pad("", 14))
    hdr += (_pad(ean, 17) + _pad(store_name, 50) + _pad("", 129) + _pad(ean, 17)
            + _pad("", 50) + _pad("", 159))
    hdr += (_pad(SUPPLIER_EAN, 17) + _pad(SUPPLIER_NAME, 50) + _pad("", 159)
            + _pad("", 17) + _pad("", 126) + _format_date(deliveryDate) + _pad("", 74))
    hdr = hdr.ljust(HEADER_WIDTH)

    lines = [hdr]
    skipped: list[str] = []
    line_no = 0
    for item in items or []:
        gtin = str(item.get("gtin") or "")
        if not gtin or gtin == "NO_MATCH":
            skipped.append(item.get("name") or "(unknown)")
            continue
        line_no += 1
        desc = _strip_diacritics(
            item.get("matchedCatalogName") or item.get("name") or "").upper()[:50]
        qty = float(item.get("quantity") or 0)
        lines.append("LIN" + _pad_left(str(line_no), 6) + "   " + _pad(gtin, 25)
                     + _pad_left(f"{qty:.3f}", 12) + _pad("PCE", 3) + _pad("", 12)
                     + _pad(desc, 50) + _pad("", 100))
    lines.append("SUM")
    return Edi(content="\r\n".join(lines), line_count=line_no, skipped=skipped)


# --- naming --------------------------------------------------------------

def _date_stamp(delivery_date: str) -> str:
    stamp = _format_date(delivery_date)
    return stamp if stamp.strip() else _today()


def _order_part(order_number: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]", "", str(order_number or ""))[:10]
    return f"_{cleaned}" if cleaned else ""


def filename(ean: str, delivery_date: str, order_number: str, stamp: str = "") -> str:
    """`ORDER_<ean tail>_<PO>_<delivery date>_<stamp>.txt`.

    The stamp keeps two uploads for the same order distinguishable; it is injectable so a
    test does not depend on the clock.
    """
    if not stamp:
        now = datetime.now()
        stamp = now.strftime("%H%M%S") + f"{now.microsecond // 1000:03d}"
    tail = str(ean or "")[-6:] or "000000"
    return (f"ORDER_{tail}{_order_part(order_number)}_{_date_stamp(delivery_date)}"
            f"_{stamp}.txt")


def change_prefix(ean: str, delivery_date: str, order_number: str) -> str:
    """The prefix of the file we already sent for this customer + day.

    A change request is corrected by hand in ORION (decision 2026-07-29), so the report
    must name the file the warehouse is looking for.
    """
    tail = str(ean or "")[-6:] or "000000"
    return f"ORDER_{tail}{_order_part(order_number)}_{_date_stamp(delivery_date)}_"


def orion_path(name: str) -> str:
    return f"{ORION_DIR}\\{name}"


# --- the ledger ----------------------------------------------------------

DOC_DATE_AT = 3 + 13 + 2 + MAX_ORDER_NUMBER + 14     # the HDR's creation-date field
DOC_DATE_LEN = 8


def content_hash(content: str) -> str:
    """Hash the ORDER, not the paperwork.

    The HDR carries the day the document was written, so the same order rebuilt after
    midnight has different bytes. Hashing those bytes made the ledger blind to exactly the
    retry it exists to stop (#51), so the creation date is blanked before hashing. Nothing
    else is normalized: a different quantity, card or recipient still hashes differently.
    """
    normalized = (content[:DOC_DATE_AT]
                  + " " * DOC_DATE_LEN
                  + content[DOC_DATE_AT + DOC_DATE_LEN:])
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


# #153: how long a bare (unconfirmed) claim is trusted to mean "another worker may
# genuinely be mid-upload right now". Plays the SAME role as db.CLAIM_STALE_MINUTES
# does for the messages.processing_at claim guard — but is a DELIBERATELY SEPARATE
# constant, not an import of that one: this is a purely internal Python-owned choice
# for a completely different table (edi_sent, not messages). They currently share a
# value by coincidence, not by contract — importing one into the other would wrongly
# couple two independent knobs. (Corrected #271, 2026-08-13: db.CLAIM_STALE_MINUTES
# is NOT actually provably matched to an n8n dispatcher window — see db.py's own
# updated comment on that constant for what a live check actually found.)
CLAIM_STALE_MINUTES = 10


def claim_send(conn, customer_ean: str, delivery_date: str, content: str,
               name: str) -> bool:
    """Claim the right to upload this exact document, or reclaim an orphaned one.

    False = a CONFIRMED upload already exists for this identity, or another claim is
    still fresh (< CLAIM_STALE_MINUTES) and may be mid-upload right now.

    Two-phase (#153): a bare claim (uploaded_at IS NULL) is only provisional. A crash
    between claim and upload is recoverable through `release_send` when the run is
    still alive to run its `except` block — but a run that dies harder (killed,
    restarted) never gets that chance, and the claim survives as an orphan. Reading an
    unconfirmed, stale orphan as "already sent" loses the order silently forever; a
    real duplicate upload is the alternative and is NOT recoverable — it creates a
    second order in ORION (#51). Reclaiming the orphan is therefore the safe direction.

    The reclaim is atomic: `DO UPDATE ... WHERE` is evaluated by Postgres per-row as
    part of conflict resolution itself, so two workers racing this same call can never
    both win — only one INSERT's conflicting UPDATE actually matches the WHERE clause
    and returns a row; the other sees no row updated and gets nothing back.
    """
    row = conn.execute(
        """INSERT INTO edi_sent (customer_ean, delivery_date, content_sha256, filename)
           VALUES (%s, %s, %s, %s)
           ON CONFLICT (customer_ean, delivery_date, content_sha256)
           DO UPDATE SET sent_at = now(), filename = EXCLUDED.filename
           WHERE edi_sent.uploaded_at IS NULL
             AND edi_sent.sent_at < now() - make_interval(mins => %s)
           RETURNING id""",
        (str(customer_ean or ""), str(delivery_date or ""), content_hash(content), name,
         CLAIM_STALE_MINUTES),
    ).fetchone()
    if row is None:
        log.warning("EDI already sent (or claimed within %sm) for %s / %s — refusing "
                    "a duplicate upload", CLAIM_STALE_MINUTES, customer_ean, delivery_date)
    return row is not None


def claim_send_or_identify(conn, customer_ean: str, delivery_date: str, content: str,
                           name: str) -> tuple[bool, bool]:
    """`claim_send()` PLUS an atomic answer to "is the row that refused me a genuinely
    CONFIRMED upload, or just someone else's fresh/unconfirmed claim?" (#271) — built on
    the shared `claim.claim_or_identify()` primitive (the same CTE shape #216 proved for
    `desadv.claim_send_or_identify()`), so this closes the identical TOCTOU class a
    `claim_send()` call followed by a SEPARATE `uploaded_at` read would leave open.

    `claim_send()` itself is UNCHANGED and stays the entry point for `pipeline.py`
    (`ai_orders`'s live engine) — this is a NEW function, added alongside it, for a
    caller (`static_worker._ship`) that needs to tell the two refusal reasons apart
    to report them honestly (#271's own finding: today `static_worker._ship` reports
    BOTH as "already sent", which is simply false for the unconfirmed case — it can
    only mis-report which stage an event belongs to, never cause a double-upload,
    since the underlying claim is still the same atomic `ON CONFLICT ... WHERE`).

    Returns `(claimed, confirmed)`:
    - `claimed=True` — the claim was taken (a fresh insert or an eligible stale
      reclaim); `confirmed` is always `False` (nothing to report — proceed to upload).
    - `claimed=False, confirmed=True` — a CONFIRMED upload already exists for this
      EXACT document (same customer + delivery date + content hash) — a genuine
      duplicate, safe to skip silently and report as "already sent".
    - `claimed=False, confirmed=False` — another claim is merely fresh/UNCONFIRMED —
      someone else may be mid-upload RIGHT NOW; nothing has necessarily reached ORION
      yet, so this must NOT be reported as "already sent".
    """
    ean = str(customer_ean or "")
    delivery = str(delivery_date or "")
    chash = content_hash(content)
    insert_sql = (
        "INSERT INTO edi_sent (customer_ean, delivery_date, content_sha256, filename) "
        "VALUES (%s, %s, %s, %s) "
        "ON CONFLICT (customer_ean, delivery_date, content_sha256) "
        "DO UPDATE SET sent_at = now(), filename = EXCLUDED.filename "
        "WHERE edi_sent.uploaded_at IS NULL "
        "AND edi_sent.sent_at < now() - make_interval(mins => %s) "
        "RETURNING NULL::boolean")
    identify_sql = (
        "SELECT (uploaded_at IS NOT NULL) FROM edi_sent "
        "WHERE customer_ean = %s AND delivery_date = %s AND content_sha256 = %s")
    claimed, info = claim_mod.claim_or_identify(
        conn,
        insert_sql=insert_sql,
        insert_params=(ean, delivery, chash, name, CLAIM_STALE_MINUTES),
        identify_sql=identify_sql,
        identify_params=(ean, delivery, chash))
    confirmed = bool(info[0]) if (info and info[0] is not None) else False
    if not claimed:
        if confirmed:
            log.warning("EDI already CONFIRMED-sent for %s / %s — refusing a "
                        "duplicate upload", customer_ean, delivery_date)
        else:
            log.warning("EDI claim still fresh (< %sm) and UNCONFIRMED for %s / %s "
                        "— refusing a duplicate upload", CLAIM_STALE_MINUTES,
                        customer_ean, delivery_date)
    return claimed, confirmed


def confirm_sent(conn, customer_ean: str, delivery_date: str, content: str,
                 pg_dsn: str = "") -> None:
    """Stamp the claim as a genuinely CONFIRMED upload — call this ONLY after the
    upload actually succeeded, never optimistically alongside the claim. Until this
    runs, the claim stays reclaimable by `claim_send` once it goes stale (#153).

    By the time this runs the document is ALREADY physically in ORION — losing this
    one write is strictly worse than the few seconds a retry costs, because an
    unconfirmed claim left behind would eventually go stale and `claim_send` would
    reclaim it for a genuine SECOND upload (review finding, PR #176: this narrows that
    residual window from "the whole upload" down to "this one UPDATE", not to zero).
    Retries a few times; a `pg_dsn` lets it replace `conn` with a fresh connection
    between attempts, since a dropped connection cannot simply be reused. If every
    attempt still fails, this re-raises — the caller's own failure handling (retrying
    the whole message later) then surfaces the problem loudly instead of silently
    losing the confirmation.
    """
    ean = str(customer_ean or "")
    delivery = str(delivery_date or "")
    chash = content_hash(content)
    stmt = ("UPDATE edi_sent SET uploaded_at = now() "
            "WHERE customer_ean = %s AND delivery_date = %s AND content_sha256 = %s")
    attempts = 4
    for attempt in range(1, attempts + 1):
        try:
            conn.execute(stmt, (ean, delivery, chash))
            log.info("EDI confirmed sent for %s / %s", customer_ean, delivery_date)
            return
        except Exception:
            log.exception("confirm_sent attempt %d/%d failed for %s / %s — the "
                          "document IS already uploaded, only the confirmation write "
                          "failed so far", attempt, attempts, customer_ean, delivery_date)
            if attempt == attempts:
                raise
            if pg_dsn:
                try:
                    conn = psycopg.connect(pg_dsn, autocommit=True)
                except Exception:
                    log.exception("reconnect for confirm_sent retry failed")
            time.sleep(1)


def release_send(conn, customer_ean: str, delivery_date: str, content: str) -> None:
    """Give the claim back after a failed upload, so the order can be retried."""
    conn.execute(
        """DELETE FROM edi_sent
            WHERE customer_ean = %s AND delivery_date = %s AND content_sha256 = %s""",
        (str(customer_ean or ""), str(delivery_date or ""), content_hash(content)))
