"""ORION EDI writer + the send ledger (#64).

ORION reads a fixed-width file: a column shifted by one character is a wrong order. The
layout below is a faithful port of the production `ASSEMBLE AND GENERATE EDI` Code node,
and `tests/fixtures/edi_reference.json` holds bytes generated by running THAT node under
node — so the test is parity with what the warehouse receives today.

The ledger closes the duplicate-upload risk (#51): (customer, delivery date, content
hash) may be claimed once. A failed upload releases its claim so the order can be retried.
"""
from __future__ import annotations

import hashlib
import logging
import re
import unicodedata
from dataclasses import dataclass
from datetime import UTC, datetime

log = logging.getLogger("orders.edi")

SUPPLIER_EAN = "8586013743063"
SUPPLIER_NAME = "SLOVNORMAL, s.r.o."
HEADER_WIDTH = 1157
ORION_DIR = "C:\\ORION\\COMMUNICATOR\\data\\in"
# ORION truncates a longer PO; the tail is the significant part.
MAX_ORDER_NUMBER = 15

_DIACRITICS = {
    "á": "a", "ä": "a", "č": "c", "ď": "d", "é": "e", "í": "i", "ĺ": "l", "ľ": "l",
    "ň": "n", "ó": "o", "ô": "o", "ŕ": "r", "š": "s", "ť": "t", "ú": "u", "ý": "y",
    "ž": "z",
}


@dataclass
class Edi:
    content: str
    line_count: int
    skipped: list[str]


def _strip_diacritics(text: str) -> str:
    """Fold to ASCII the way the production generator does.

    It maps the Slovak letters explicitly and leaves anything else alone, so characters
    like "–" or "ĽŠŤ" that are NOT in its table survive there — here they are folded via
    NFKD and finally dropped, because ORION's fixed-width reader is ASCII. Both paths
    agree on every character the live pipeline actually emits (pinned by the fixture).
    """
    out = []
    for ch in str(text or ""):
        mapped = _DIACRITICS.get(ch) or _DIACRITICS.get(ch.lower())
        if mapped:
            out.append(mapped.upper() if ch.isupper() else mapped)
            continue
        if ord(ch) < 128:
            out.append(ch)
            continue
        folded = "".join(c for c in unicodedata.normalize("NFKD", ch)
                         if not unicodedata.combining(c))
        out.append("".join(c for c in folded if ord(c) < 128))
    return "".join(out)


def _pad(text, width: int) -> str:
    s = _strip_diacritics(text)
    return s[:width] if len(s) >= width else s + " " * (width - len(s))


def _pad_left(text, width: int) -> str:
    s = str(text or "")
    return s[:width] if len(s) >= width else " " * (width - len(s)) + s


def _format_date(value: str) -> str:
    """YYYYMMDD from DD.MM.YYYY or ISO; 8 spaces when there is no usable date.

    Both shapes are accepted because the verify stage sometimes reformats the delivery
    date to ISO — dropping it from the header would lose the expedition date.
    """
    s = str(value or "").strip()
    iso = re.match(r"^(\d{4})-(\d{2})-(\d{2})$", s)
    if iso:
        return iso.group(1) + iso.group(2) + iso.group(3)
    parts = s.split(".")
    if len(parts) != 3:
        return " " * 8
    year = parts[2].strip()
    if len(year) == 2:
        year = "20" + year
    return year + parts[1].strip().rjust(2, "0") + parts[0].strip().rjust(2, "0")


def _today() -> str:
    return datetime.now(UTC).strftime("%Y%m%d")


def build(ean: str, store: str, orderNumber: str, deliveryDate: str,  # noqa: N803
          items: list[dict]) -> Edi:
    """The fixed-width document. Unmatched items are skipped and returned by name.

    Parameter names match the production node's arguments so the fixture can be applied
    with `**case["input"]` and any drift shows up as a byte diff.
    """
    order_no = str(orderNumber or "")[-MAX_ORDER_NUMBER:]
    store_name = _strip_diacritics(store or "Zakaznik")
    ean = str(ean or "")

    hdr = ("HDR" + _pad(SUPPLIER_EAN, 13) + "  " + _pad(order_no, 15) + _pad("", 14)
           + _today() + "   ")
    hdr += (_pad(ean, 17) + _pad(store_name, 50) + _pad("", 50) + _pad("", 50)
            + _pad("", 30) + _pad("", 15) + _pad("", 14))
    hdr += (_pad(ean, 17) + _pad(store_name, 50) + _pad("", 129) + _pad(ean, 17)
            + _pad("", 50) + _pad("", 159))
    hdr += (_pad(SUPPLIER_EAN, 17) + _pad(SUPPLIER_NAME, 50) + _pad("", 159)
            + _pad("", 17) + _pad("", 126) + _format_date(deliveryDate) + _pad("", 74))
    hdr = hdr.ljust(HEADER_WIDTH)

    lines = [hdr]
    skipped: list[str] = []
    line_no = 0
    for item in items or []:
        gtin = str(item.get("gtin") or "")
        if not gtin or gtin == "NO_MATCH":
            skipped.append(item.get("name") or "(unknown)")
            continue
        line_no += 1
        desc = _strip_diacritics(
            item.get("matchedCatalogName") or item.get("name") or "").upper()[:50]
        qty = float(item.get("quantity") or 0)
        lines.append("LIN" + _pad_left(str(line_no), 6) + "   " + _pad(gtin, 25)
                     + _pad_left(f"{qty:.3f}", 12) + _pad("PCE", 3) + _pad("", 12)
                     + _pad(desc, 50) + _pad("", 100))
    lines.append("SUM")
    return Edi(content="\r\n".join(lines), line_count=line_no, skipped=skipped)


# --- naming --------------------------------------------------------------

def _date_stamp(delivery_date: str) -> str:
    stamp = _format_date(delivery_date)
    return stamp if stamp.strip() else _today()


def _order_part(order_number: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]", "", str(order_number or ""))[:10]
    return f"_{cleaned}" if cleaned else ""


def filename(ean: str, delivery_date: str, order_number: str, stamp: str = "") -> str:
    """`ORDER_<ean tail>_<PO>_<delivery date>_<stamp>.txt`.

    The stamp keeps two uploads for the same order distinguishable; it is injectable so a
    test does not depend on the clock.
    """
    if not stamp:
        now = datetime.now()
        stamp = now.strftime("%H%M%S") + f"{now.microsecond // 1000:03d}"
    tail = str(ean or "")[-6:] or "000000"
    return (f"ORDER_{tail}{_order_part(order_number)}_{_date_stamp(delivery_date)}"
            f"_{stamp}.txt")


def change_prefix(ean: str, delivery_date: str, order_number: str) -> str:
    """The prefix of the file we already sent for this customer + day.

    A change request is corrected by hand in ORION (decision 2026-07-29), so the report
    must name the file the warehouse is looking for.
    """
    tail = str(ean or "")[-6:] or "000000"
    return f"ORDER_{tail}{_order_part(order_number)}_{_date_stamp(delivery_date)}_"


def orion_path(name: str) -> str:
    return f"{ORION_DIR}\\{name}"


# --- the ledger ----------------------------------------------------------

def content_hash(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def claim_send(conn, customer_ean: str, delivery_date: str, content: str,
               name: str) -> bool:
    """Claim the right to upload this exact document. False = already sent.

    Claimed BEFORE the upload: a crash between claim and upload is recoverable through
    `release_send`, while a duplicate upload is not recoverable at all — it creates a
    second order in ORION (#51).
    """
    row = conn.execute(
        """INSERT INTO edi_sent (customer_ean, delivery_date, content_sha256, filename)
           VALUES (%s, %s, %s, %s)
           ON CONFLICT (customer_ean, delivery_date, content_sha256) DO NOTHING
           RETURNING id""",
        (str(customer_ean or ""), str(delivery_date or ""), content_hash(content), name),
    ).fetchone()
    if row is None:
        log.warning("EDI already sent for %s / %s — refusing a duplicate upload",
                    customer_ean, delivery_date)
    return row is not None


def release_send(conn, customer_ean: str, delivery_date: str, content: str) -> None:
    """Give the claim back after a failed upload, so the order can be retried."""
    conn.execute(
        """DELETE FROM edi_sent
            WHERE customer_ean = %s AND delivery_date = %s AND content_sha256 = %s""",
        (str(customer_ean or ""), str(delivery_date or ""), content_hash(content)))
